version: '3.9'

services:
  web:
    container_name: vozyTest
    restart: always
    build: .
    ports:
     - "3000:3000"
    links:
      - mongo
    volumes:
      - .:/usr/src/app
  mongo:
    container_name: vozyMongodb
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: vozy
      MONGO_INITDB_ROOT_PASSWORD: test123
      MONGO_INITDB_DATABASE: vozydb
    ports:
     - "27018:27017"
    logging:
      driver: none